### ISSUE TITLE
Get the app running with docker-compose

### ISSUE THREAD

**Issue by ericelliott** [jshomes/JSHomes-Platform#19]
We're trying to get the platform working on docker containers. We want to accomplish the following objectives:

*  **Configuration via environment variables** for easy multi-environment deployments and horizontal scaling
*  **Extremely easy development environment setup** for new contributors. A few minutes and a short README should be enough to get the app to spin up on a new machine.
* **Automated deploys**

I believe Docker containers can solve these problems effectively, and automate most of the process.

See the [docker experiment docs](https://github.com/jshomes/JSHomes-Platform/blob/master/docs/experimental/docker.md) for more details

## Problem

[Blocking #20](https://github.com/jshomes/JSHomes-Platform/issues/20)

I and many contributors will be working on Mac with OS X. Mac doesn't have first-class support for Docker containers. I'm trying to use boot2docker. There are [instructions for folder sharing](https://github.com/boot2docker/boot2docker#folder-sharing) with boot2docker. I'm having trouble translating those instructions into a `docker-compose.yml` and a mac bash script to start it up.

When I try to create the samba share, I see:

```
$ docker run --rm -v /usr/local/bin/docker:/docker -v /var/run/docker.sock:/docker.sock svendowideit/samba data
Error: No such image or container: data
Error: data is not a valid container name: data

please run with:
   docker run --rm -v $(which docker):/docker -v /var/run/docker.sock:/docker.sock -e DOCKER_HOST svendowideit/samba data

 OR - depending on your Docker Host's socket connection and location of its docker binary

   docker run --rm -v /usr/local/bin/docker:/docker -e DOCKER_HOST svendowideit/samba data
````

## Reproduce

See the [broken instructions](https://github.com/jshomes/JSHomes-Platform/blob/master/docs/experimental/docker.md#docker-compose).

## Acceptance test

* [x] Mount wp-content from a docker volume
* [x] Successfully modify docker volume contents from OS X host editor of choice

## References

#4

**Comment by evanboho** [comment]
I believe the last `data` in the command (which in the example is `my-data`) refers to a named container. In the first line of the example, they do `docker run -v /data --name my-data busybox true` which names the container `my-data`.

**Comment by ericelliott** [comment]
Could you create a PR with a (tested) fix for the doc? See the docker experiment docs link above...

**Comment by ericelliott** [comment]
@mattma Let's discuss here instead of Twitter. =)

**Comment by ericelliott** [comment]
See [@mattma's fork](https://github.com/mattma/JSHomes-Platform) for work in progress

**Comment by mattma** [comment]
I will pick up where I left off today. I am currently working on the connection between Wordpress and MySQL.

**Comment by ericelliott** [comment]
Great. =)

**Comment by mattma** [comment]
I am continuously working on this issue now. It turns out that Wordpress and MySql are all installed correctly, but I do need a Web Server to serve my PHP files. 

I wish that I could install "Node" and call "npm start" to kick off my server. Well, that is not the case. I need to figure out how to use "apache" in this case. I am not too familiar with it. It took a little longer than I expected. I won't give up yet. I will keep you posted.

**Comment by ericelliott** [comment]
> I do need a Web Server to serve my PHP files.

Apache is fine.

Later we'll put Nginx in front of it (on a different redundant load balancer), and reverse proxy to Apache/WordPress & Node.js. We'll move routes from the WordPress proxy to the Node proxy as we port the needed features.

Apache is needed for WordPress because a LOT of the security plugins assume Apache. This is a temporary hack, and we're not going to reinvent the WordPress wheel.

Sound good? =)

**Comment by ericelliott** [comment]
This is currently blocking just about everything. Do you have an update? Maybe you could open a Work in Progress PR?

**Comment by mattma** [comment]
I work on this issue part time. I will try to wrap up this weekend and have an update here.

**Comment by ericelliott** [comment]
Thanks. =)

**Comment by mattma** [comment]
Still working on. It is a hard problem. Could you give me two more days? I know it is blocking the process. I rather to make it right at the first time. Since I have not using MySQL, Apache, PHP for a couple of years, Those domain knowledge hit me hard rather than working with Vagrant and Docker.

**Comment by ericelliott** [comment]
=)

**Comment by jaime5x5** [comment]
So I am pretty experienced with WP and Apache. Is there something I can help with here? I need an open source project on my resume and this is a cause I can get behind. I have basic training in Java as OOP language and some C for functional language. WP has inspired my PHP and MySQL endeavors.  Two years network administration and design training and two years computer information systems training (CS without the Calculus). :)

**Comment by ericelliott** [comment]
Welcome, @jaime5x5 =)

@mattma Can you open a work-in-progress pull request that we can look at & comment on?

Jaime5x5: Another thing you could be doing while we wait is setting up [fake git submodules](http://debuggable.com/posts/git-fake-submodules:4b563ee4-f3cc-4061-967e-0e48cbdd56cb) for each of the WordPress plugins we need. You can issue a pull request for each one after putting them in the [plugins directory](https://github.com/jshomes/JSHomes-Platform/tree/master/platform/wp-content/plugins).

After @mattma's PR is finished, we can merge the branches, copying all the plugins into @mattma's branch so that they will be available to the new WordPress container instance.

**Comment by mattma** [comment]
@ericelliott @jaime5x5 

I do not need any help at the moment. I have got wordpress installation show up in Vagrant environment. I will inform you sometimes today when you could start testing. Thank you for being so patient.

**Comment by mattma** [comment]
PR has been raised. https://github.com/jshomes/JSHomes-Platform/pull/38

**Comment by ericelliott** [comment]
This looks good. Thanks @mattma!
